import type { MediaItem } from "@/shared/media";

export const outputSections = [
  { key: "curriculum", label: "Curriculum" },
  { key: "didactic-methods", label: "Didactic Methods" },
  { key: "dissemination", label: "Dissemination" },
  { key: "learning-activities", label: "Learning Activities" },
] as const;

export const outputItems: MediaItem[] = [
  // ── Curriculum ──
  {
    index: 0,
    title: "Report on Inventory and Analysis of Required Topics",
    description: "D2.1.1 – Report on inventory and analysis of required topics",
    src: "/outputs/curriculum/d2.1.1_report_on_inventory_and_analysis_of_required_topics.pdf",
    type: "pdf",
    section: "curriculum",
  },
  {
    index: 1,
    title: "List of Topics to Use in Curriculum",
    description: "D2.1.2 – List of topics to use in curriculum",
    src: "/outputs/curriculum/d2.1.2-_list_of_topics_to_use_in_curriculum.pdf",
    type: "pdf",
    section: "curriculum",
  },
  {
    index: 2,
    title: "Competences and Curriculum",
    description: "D2.2 and D2.3 – Competences and Curriculum",
    src: "/outputs/curriculum/d2.2._and_d2.3_competences_and_curriculum.pdf",
    type: "pdf",
    section: "curriculum",
  },

  // ── Didactic Methods ──
  {
    index: 3,
    title: "Handbook for Didactic Methods",
    description: "D2.4.1 – Handbook for didactic methods",
    src: "/outputs/didactic-methods/d.2.4.1-handbook_for_didactic_methods.pdf",
    type: "pdf",
    section: "didactic-methods",
  },
  {
    index: 4,
    title: "e-Handbook for Assessment Methods",
    description: "D2.5.1 – e-Handbook for assessment methods",
    src: "/outputs/didactic-methods/d2.5.1_-e-handbook_for_assessement_methods.pdf",
    type: "pdf",
    section: "didactic-methods",
  },

  // ── Dissemination ──
  {
    index: 5,
    title: "Conference ADEM 2025",
    description: "Conference ADEM 2025 presentation",
    src: "/outputs/dissemination/confadem2025.pdf",
    type: "pdf",
    section: "dissemination",
  },
  {
    index: 6,
    title: "Conference ASR 2025",
    description: "Conference ASR 2025 presentation",
    src: "/outputs/dissemination/confasr2025.pdf",
    type: "pdf",
    section: "dissemination",
  },
  {
    index: 7,
    title: "First Year Progress Dissemination Report",
    description: "First year progress dissemination report",
    src: "/outputs/dissemination/first_year_progress_dissemination_report.pdf",
    type: "pdf",
    section: "dissemination",
  },
  {
    index: 8,
    title: "Poster",
    description: "Dissemination poster",
    src: "/outputs/dissemination/poster.pdf",
    type: "pdf",
    section: "dissemination",
  },
  {
    index: 9,
    title: "Rollup 1",
    description: "Dissemination rollup banner 1",
    src: "/outputs/dissemination/rollup1.pdf",
    type: "pdf",
    section: "dissemination",
  },
  {
    index: 10,
    title: "Rollup 2",
    description: "Dissemination rollup banner 2",
    src: "/outputs/dissemination/rollup2.pdf",
    type: "pdf",
    section: "dissemination",
  },
  {
    index: 11,
    title: "Rollup 3",
    description: "Dissemination rollup banner 3",
    src: "/outputs/dissemination/rollup3.pdf",
    type: "pdf",
    section: "dissemination",
  },
  {
    index: 12,
    title: "Webinar ASR 2025",
    description: "Webinar ASR 2025 presentation",
    src: "/outputs/dissemination/webinarasr2025.pdf",
    type: "pdf",
    section: "dissemination",
  },
  {
    index: 13,
    title: "Dissemination Video",
    description: "Dissemination video",
    src: "/outputs/dissemination/video.mp4",
    type: "video",
    section: "dissemination",
  },
  {
    index: 14,
    title: "Dissemination Product 1",
    description: "Dissemination product image",
    src: "/outputs/dissemination/diss_prod1.webp",
    type: "image",
    section: "dissemination",
  },
  {
    index: 15,
    title: "Dissemination Product 2",
    description: "Dissemination product image",
    src: "/outputs/dissemination/diss_prod2.webp",
    type: "image",
    section: "dissemination",
  },
  {
    index: 16,
    title: "Dissemination Product 3",
    description: "Dissemination product image",
    src: "/outputs/dissemination/diss_prod3.webp",
    type: "image",
    section: "dissemination",
  },
  {
    index: 17,
    title: "Dissemination Product 4",
    description: "Dissemination product image",
    src: "/outputs/dissemination/diss_prod4.webp",
    type: "image",
    section: "dissemination",
  },
  {
    index: 18,
    title: "Dissemination Product 5",
    description: "Dissemination product image",
    src: "/outputs/dissemination/diss_prod5.webp",
    type: "image",
    section: "dissemination",
  },
  {
    index: 19,
    title: "Dissemination Product 6",
    description: "Dissemination product image",
    src: "/outputs/dissemination/diss_prod6.webp",
    type: "image",
    section: "dissemination",
  },
  {
    index: 20,
    title: "Dissemination Product 7",
    description: "Dissemination product image",
    src: "/outputs/dissemination/diss_prod7.webp",
    type: "image",
    section: "dissemination",
  },
  {
    index: 21,
    title: "Dissemination Product 8",
    description: "Dissemination product image",
    src: "/outputs/dissemination/diss_prod8.webp",
    type: "image",
    section: "dissemination",
  },

  // ── Learning Activities – Pilot Courses ──
  {
    index: 22,
    title: "Invitation – Pilot Course C1",
    description: "Invitation for pilot course C1 (15.01.2026)",
    src: "/outputs/learning-activities/pilot-courses/invitation-course_c1-15.01.2026.pdf",
    type: "pdf",
    section: "learning-activities",
  },
  {
    index: 23,
    title: "Invitation – Pilot Course C2",
    description: "Invitation for pilot course C2 (22.01.2026)",
    src: "/outputs/learning-activities/pilot-courses/invitation-course_c2-22.01.2026.pdf",
    type: "pdf",
    section: "learning-activities",
  },
  {
    index: 24,
    title: "Invitation – Pilot Course C3",
    description: "Invitation for pilot course C3 (29.01.2026)",
    src: "/outputs/learning-activities/pilot-courses/invitation-course_c3-29.01.2026.webp",
    type: "image",
    section: "learning-activities",
  },
  {
    index: 25,
    title: "C1 – UCV Onsite",
    description: "Pilot course C1 – UCV onsite photo",
    src: "/outputs/learning-activities/pilot-courses/c1-ucv_onsite.webp",
    type: "image",
    section: "learning-activities",
  },
  {
    index: 26,
    title: "C1 – UBB Onsite",
    description: "Pilot course C1 – UBB onsite photo",
    src: "/outputs/learning-activities/pilot-courses/c1-ubb_onsite.webp",
    type: "image",
    section: "learning-activities",
  },
  {
    index: 27,
    title: "C1 – Image 1",
    description: "Pilot course C1 – Photo 1",
    src: "/outputs/learning-activities/pilot-courses/c1-image1.webp",
    type: "image",
    section: "learning-activities",
  },
  {
    index: 28,
    title: "C1 – Image 2",
    description: "Pilot course C1 – Photo 2",
    src: "/outputs/learning-activities/pilot-courses/c1-image2.webp",
    type: "image",
    section: "learning-activities",
  },
  {
    index: 29,
    title: "C1 – Image 3",
    description: "Pilot course C1 – Photo 3",
    src: "/outputs/learning-activities/pilot-courses/c1-image3.webp",
    type: "image",
    section: "learning-activities",
  },
  {
    index: 30,
    title: "C1 – Image 4",
    description: "Pilot course C1 – Photo 4",
    src: "/outputs/learning-activities/pilot-courses/c1-image4.webp",
    type: "image",
    section: "learning-activities",
  },
  {
    index: 31,
    title: "C2 – UCV Onsite 1",
    description: "Pilot course C2 – UCV onsite photo 1",
    src: "/outputs/learning-activities/pilot-courses/c2-ucv_onsite1.webp",
    type: "image",
    section: "learning-activities",
  },
  {
    index: 32,
    title: "C2 – UCV Onsite 2",
    description: "Pilot course C2 – UCV onsite photo 2",
    src: "/outputs/learning-activities/pilot-courses/c2-ucv_onsite2.webp",
    type: "image",
    section: "learning-activities",
  },
  {
    index: 33,
    title: "C2 – UCV Onsite 3",
    description: "Pilot course C2 – UCV onsite photo 3",
    src: "/outputs/learning-activities/pilot-courses/c2-ucv_onsite3.webp",
    type: "image",
    section: "learning-activities",
  },
  {
    index: 34,
    title: "C2 – UBB Onsite",
    description: "Pilot course C2 – UBB onsite photo",
    src: "/outputs/learning-activities/pilot-courses/c2-ubb_onsite.webp",
    type: "image",
    section: "learning-activities",
  },
  {
    index: 35,
    title: "C2 – Image 1",
    description: "Pilot course C2 – Photo 1",
    src: "/outputs/learning-activities/pilot-courses/c2-image1.webp",
    type: "image",
    section: "learning-activities",
  },
  {
    index: 36,
    title: "C2 – Image 2",
    description: "Pilot course C2 – Photo 2",
    src: "/outputs/learning-activities/pilot-courses/c2-image2.webp",
    type: "image",
    section: "learning-activities",
  },
  {
    index: 37,
    title: "C3 – UCV Onsite",
    description: "Pilot course C3 – UCV onsite photo",
    src: "/outputs/learning-activities/pilot-courses/c3-ucv_onsite.webp",
    type: "image",
    section: "learning-activities",
  },
  {
    index: 38,
    title: "C3 – UBB Onsite",
    description: "Pilot course C3 – UBB onsite photo",
    src: "/outputs/learning-activities/pilot-courses/c3-ubb_onsite.webp",
    type: "image",
    section: "learning-activities",
  },
  {
    index: 39,
    title: "C3 – Image 1",
    description: "Pilot course C3 – Photo 1",
    src: "/outputs/learning-activities/pilot-courses/c3-image1.webp",
    type: "image",
    section: "learning-activities",
  },
  {
    index: 40,
    title: "C3 – Image 2",
    description: "Pilot course C3 – Photo 2",
    src: "/outputs/learning-activities/pilot-courses/c3-image2.webp",
    type: "image",
    section: "learning-activities",
  },
  {
    index: 41,
    title: "C3 – Image 3",
    description: "Pilot course C3 – Photo 3",
    src: "/outputs/learning-activities/pilot-courses/c3-image3.webp",
    type: "image",
    section: "learning-activities",
  },
  {
    index: 42,
    title: "C3 – Image 4",
    description: "Pilot course C3 – Photo 4",
    src: "/outputs/learning-activities/pilot-courses/c3-image4.webp",
    type: "image",
    section: "learning-activities",
  },

  // ── Learning Activities – Webinars ──
  {
    index: 43,
    title: "Webinar 1",
    description: "Learning activities – Webinar 1",
    src: "/outputs/learning-activities/webinars/web1.pdf",
    type: "pdf",
    section: "learning-activities",
  },
  {
    index: 44,
    title: "Webinar 2",
    description: "Learning activities – Webinar 2",
    src: "/outputs/learning-activities/webinars/web2.pdf",
    type: "pdf",
    section: "learning-activities",
  },
  {
    index: 45,
    title: "Webinar 3",
    description: "Learning activities – Webinar 3",
    src: "/outputs/learning-activities/webinars/web3.pdf",
    type: "pdf",
    section: "learning-activities",
  },
];
